apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - command:
        - /shared/argocd-dex
        - rundex
        imagePullPolicy: Always
        name: dex
        ports:
        - containerPort: 5556
          name: http
          protocol: TCP
        - containerPort: 5557
          name: grpc
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /shared
          name: static-files
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - cp
        - /usr/local/bin/argocd
        - /shared/argocd-dex
        image: quay.io/argoproj/argocd:v2.0.0
        imagePullPolicy: Always
        name: copyutil
        resources: {}
