apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  dex:
    openShiftOAuth: true
    image: quay.io/redhat-cop/dex
    version: v2.22.0-openshift
  image: quay.io/argoproj/argocd
  resourceCustomizations: |
  route.openshift.io/Route:
    ignoreDifferences: |
      jsonPointers:
      - /spec/host
  rbac:
    policy: |
      g, admins, role:admin
      g, developer, role:developer
    scopes: '[groups]'
  server:
    route:
      enabled: true
  version: v2.0.0
  initialRepositories: |
    - name: sample-app
      type: git
      url: https://github.com/siamaksade/openshift-gitops-getting-started
      path: app
